// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhfFDNdmsproxLuxBa-lWlSXyEoWCR7-g',
    appId: '1:1055389109779:web:1d64f9857f8e8c126879e6',
    messagingSenderId: '1055389109779',
    projectId: 'tgbc-app',
    authDomain: 'tgbc-app.firebaseapp.com',
    storageBucket: 'tgbc-app.firebasestorage.app',
    measurementId: 'G-1Z4114KDD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmt0Sp9GOj0YxUYrtbn_fuwZ7HabGrZpk',
    appId: '1:1055389109779:android:31f79506d9cd26b56879e6',
    messagingSenderId: '1055389109779',
    projectId: 'tgbc-app',
    storageBucket: 'tgbc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywI_EFwdOxHqk3gjTPVDcXJdb5K4INCc',
    appId: '1:1055389109779:ios:537924843da2cf526879e6',
    messagingSenderId: '1055389109779',
    projectId: 'tgbc-app',
    storageBucket: 'tgbc-app.firebasestorage.app',
    iosBundleId: 'com.example.tgbcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywI_EFwdOxHqk3gjTPVDcXJdb5K4INCc',
    appId: '1:1055389109779:ios:537924843da2cf526879e6',
    messagingSenderId: '1055389109779',
    projectId: 'tgbc-app',
    storageBucket: 'tgbc-app.firebasestorage.app',
    iosBundleId: 'com.example.tgbcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhfFDNdmsproxLuxBa-lWlSXyEoWCR7-g',
    appId: '1:1055389109779:web:595f808fa88bae466879e6',
    messagingSenderId: '1055389109779',
    projectId: 'tgbc-app',
    authDomain: 'tgbc-app.firebaseapp.com',
    storageBucket: 'tgbc-app.firebasestorage.app',
    measurementId: 'G-N7EW7G6VWG',
  );
}
